### PR TITLE
Added custom SB parts for better thermistor wire access

### PR DESCRIPTION
**Pull request by LobodPl**
Added 4,5mm shift in right SB wall to get better access to the thermistor wire terminal.
Before
image

After
image

### CODE REVIEW

**Comment by ITTV-tools** [comment]
Can you please upload the step file ?

**Comment by LobodPl** [comment]
> Can you please upload the step file ?
.STEP filles added with new PR.
https://github.com/bigtreetech/EBB/pull/63
There are also files on my fork repo.
https://github.com/LobodPl/EBB/tree/master

**Comment by ITTV-tools** [comment]
Thanks!

**Comment by rollduck** [comment]
Could you add these parts for the latest clockwork version?

**Pull request merged**
