### PR TITLE
Update Main_Body_EBB STL

### PR DESCRIPTION
**Pull request by Rowan2233**

### CODE REVIEW

**Comment by piechade** [comment]
It looks still like the old version and not like the final.
https://github.com/VoronDesign/Voron-Stealthburner/blob/main/STLs/Clockwork2/Direct_Drive/main_body.stl

**Comment by kocosoma** [comment]
The main body doesn't compatible with the current stealthburner motor plate... Why it was changed?

**Comment by IggyTheWolf** [comment]
This is the correct file: https://github.com/bigtreetech/EBB/commit/715629e564b63ccb8f705a548d57c549e4291d9d

The current one will not work.

**Comment by looxonline** [comment]
Fixing now.

**Pull request merged**
